package domain

import "errors"

var (
	ErrNotFound                         = errors.New("not found")
	ErrForbidden                        = errors.New("forbidden")
	ErrUnauthorized                     = errors.New("unauthorized")
	ErrConflict                         = errors.New("conflict")
	ErrInvalidInput                     = errors.New("invalid input")
	ErrNotSupported                     = errors.New("not supported")
	ErrNoPaymentRequired                = errors.New("no payment required")
	ErrNoChanges                        = errors.New("no changes")
	ErrResizeSamePlan                   = errors.New("resize target matches current plan")
	ErrResizeDisabled                   = errors.New("resize disabled")
	ErrResizeInProgress                 = errors.New("resize already in progress")
	ErrCaptchaFailed                    = errors.New("captcha failed")
	ErrInsufficientBalance              = errors.New("insufficient balance")
	ErrRealNameRequired                 = errors.New("real name required")
	ErrProvisioning                     = errors.New("provisioning")
	ErrCannotDeleteSelf                 = errors.New("cannot delete yourself")
	ErrInvalidOldPassword               = errors.New("invalid old password")
	ErrTokenUsed                        = errors.New("token already used")
	ErrTokenExpired                     = errors.New("token expired")
	ErrHostIDNotFound                   = errors.New("host id not found")
	ErrPluginsDisabled                  = errors.New("plugins disabled")
	ErrPaymentMethodRepoMissing         = errors.New("payment method repo missing")
	ErrPluginInstanceRequired           = errors.New("category/plugin_id/instance_id required")
	ErrPluginMethodUpdateRequired       = errors.New("category/plugin_id/instance_id/method/enabled required")
	ErrPluginInstanceNotEnabled         = errors.New("plugin instance not enabled/loaded")
	ErrNotPaymentPluginInstance         = errors.New("not a payment plugin instance")
	ErrPluginInstanceNotFound           = errors.New("plugin instance not found")
	ErrPluginMethodNotSupported         = errors.New("method not supported")
	ErrAutomationBindingInvalid         = errors.New("invalid automation binding")
	ErrAutomationPluginInstanceNotFound = errors.New("automation plugin instance not found")
	ErrSecurityTicketRequired           = errors.New("security ticket required")
	ErrSecurityTicketInvalid            = errors.New("invalid security ticket")
	ErrMissingBearerToken               = errors.New("missing bearer token")
	ErrEmptyToken                       = errors.New("empty token")
	ErrUnexpectedSigningMethod          = errors.New("unexpected signing method")
	ErrInvalidToken                     = errors.New("invalid token")
	ErrInvalidRole                      = errors.New("invalid role")
	ErrInvalidProbeID                   = errors.New("invalid probe id")
	ErrNoMessageChannelConfigured       = errors.New("no message channel configured")
	ErrTemplateNameRequired             = errors.New("template name required")
	ErrEmailNotBound                    = errors.New("email not bound")
	ErrEmailSenderNotConfigured         = errors.New("email sender not configured")
	ErrSMSPluginManagerUnavailable      = errors.New("sms plugin manager unavailable")
	ErrPhoneNotBound                    = errors.New("phone not bound")
	ErrSMSPluginNotConfigured           = errors.New("sms plugin not configured")
	ErrNoAvailableChannel               = errors.New("no available channel")
	ErrEmptyRefreshToken                = errors.New("empty refresh token")
	ErrInvalidRefreshToken              = errors.New("invalid refresh token")
	ErrInvalidTokenType                 = errors.New("invalid token type")
	ErrAdminServiceUnavailable          = errors.New("admin service unavailable")
	ErrGeoIPMMDBPathEmpty               = errors.New("geoip mmdb path empty")
	ErrInvalidIP                        = errors.New("invalid ip")
	ErrNonPublicIP                      = errors.New("non-public ip")
	ErrCMSPageRequired                  = errors.New("page required")
	ErrCMSPageInvalid                   = errors.New("page invalid")
	ErrCMSPageReserved                  = errors.New("page reserved")
	ErrInvalidStrategy                  = errors.New("invalid strategy")
	ErrProbeOffline                     = errors.New("probe offline")
	ErrProbeLogSessionClosed            = errors.New("probe log session closed")
)
