include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_field: ignore
    strict_top_level_inference: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    prefer_if_null_operators: ignore
    use_null_aware_elements: ignore
    unnecessary_to_list_in_spreads: ignore
    unnecessary_non_null_assertion: ignore
    unused_element: ignore
    unnecessary_underscores: ignore
    depend_on_referenced_packages: ignore
    const_with_non_const: ignore
    non_constant_list_element: ignore
    creation_with_non_type: ignore
    unused_import: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    avoid_print: false
