// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: plugin/v1/automation.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutomationService_ListAreas_FullMethodName           = "/plugin.v1.AutomationService/ListAreas"
	AutomationService_ListLines_FullMethodName           = "/plugin.v1.AutomationService/ListLines"
	AutomationService_ListPackages_FullMethodName        = "/plugin.v1.AutomationService/ListPackages"
	AutomationService_ListImages_FullMethodName          = "/plugin.v1.AutomationService/ListImages"
	AutomationService_CreateInstance_FullMethodName      = "/plugin.v1.AutomationService/CreateInstance"
	AutomationService_GetInstance_FullMethodName         = "/plugin.v1.AutomationService/GetInstance"
	AutomationService_ListInstancesSimple_FullMethodName = "/plugin.v1.AutomationService/ListInstancesSimple"
	AutomationService_Start_FullMethodName               = "/plugin.v1.AutomationService/Start"
	AutomationService_Shutdown_FullMethodName            = "/plugin.v1.AutomationService/Shutdown"
	AutomationService_Reboot_FullMethodName              = "/plugin.v1.AutomationService/Reboot"
	AutomationService_Rebuild_FullMethodName             = "/plugin.v1.AutomationService/Rebuild"
	AutomationService_ResetPassword_FullMethodName       = "/plugin.v1.AutomationService/ResetPassword"
	AutomationService_ElasticUpdate_FullMethodName       = "/plugin.v1.AutomationService/ElasticUpdate"
	AutomationService_Lock_FullMethodName                = "/plugin.v1.AutomationService/Lock"
	AutomationService_Unlock_FullMethodName              = "/plugin.v1.AutomationService/Unlock"
	AutomationService_Renew_FullMethodName               = "/plugin.v1.AutomationService/Renew"
	AutomationService_Destroy_FullMethodName             = "/plugin.v1.AutomationService/Destroy"
	AutomationService_GetPanelURL_FullMethodName         = "/plugin.v1.AutomationService/GetPanelURL"
	AutomationService_GetVNCURL_FullMethodName           = "/plugin.v1.AutomationService/GetVNCURL"
	AutomationService_GetMonitor_FullMethodName          = "/plugin.v1.AutomationService/GetMonitor"
	AutomationService_ListPortMappings_FullMethodName    = "/plugin.v1.AutomationService/ListPortMappings"
	AutomationService_AddPortMapping_FullMethodName      = "/plugin.v1.AutomationService/AddPortMapping"
	AutomationService_DeletePortMapping_FullMethodName   = "/plugin.v1.AutomationService/DeletePortMapping"
	AutomationService_FindPortCandidates_FullMethodName  = "/plugin.v1.AutomationService/FindPortCandidates"
	AutomationService_ListBackups_FullMethodName         = "/plugin.v1.AutomationService/ListBackups"
	AutomationService_CreateBackup_FullMethodName        = "/plugin.v1.AutomationService/CreateBackup"
	AutomationService_DeleteBackup_FullMethodName        = "/plugin.v1.AutomationService/DeleteBackup"
	AutomationService_RestoreBackup_FullMethodName       = "/plugin.v1.AutomationService/RestoreBackup"
	AutomationService_ListSnapshots_FullMethodName       = "/plugin.v1.AutomationService/ListSnapshots"
	AutomationService_CreateSnapshot_FullMethodName      = "/plugin.v1.AutomationService/CreateSnapshot"
	AutomationService_DeleteSnapshot_FullMethodName      = "/plugin.v1.AutomationService/DeleteSnapshot"
	AutomationService_RestoreSnapshot_FullMethodName     = "/plugin.v1.AutomationService/RestoreSnapshot"
	AutomationService_ListFirewallRules_FullMethodName   = "/plugin.v1.AutomationService/ListFirewallRules"
	AutomationService_AddFirewallRule_FullMethodName     = "/plugin.v1.AutomationService/AddFirewallRule"
	AutomationService_DeleteFirewallRule_FullMethodName  = "/plugin.v1.AutomationService/DeleteFirewallRule"
)

// AutomationServiceClient is the client API for AutomationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationServiceClient interface {
	// Catalog sync
	ListAreas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAreasResponse, error)
	ListLines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListLinesResponse, error)
	ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// Instance lifecycle
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error)
	ListInstancesSimple(ctx context.Context, in *ListInstancesSimpleRequest, opts ...grpc.CallOption) (*ListInstancesSimpleResponse, error)
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Empty, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*Empty, error)
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*Empty, error)
	Rebuild(ctx context.Context, in *RebuildRequest, opts ...grpc.CallOption) (*Empty, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Empty, error)
	ElasticUpdate(ctx context.Context, in *ElasticUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Empty, error)
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*Empty, error)
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*Empty, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*Empty, error)
	GetPanelURL(ctx context.Context, in *GetPanelURLRequest, opts ...grpc.CallOption) (*GetPanelURLResponse, error)
	GetVNCURL(ctx context.Context, in *GetVNCURLRequest, opts ...grpc.CallOption) (*GetVNCURLResponse, error)
	GetMonitor(ctx context.Context, in *GetMonitorRequest, opts ...grpc.CallOption) (*GetMonitorResponse, error)
	// Port mapping (optional)
	ListPortMappings(ctx context.Context, in *ListPortMappingsRequest, opts ...grpc.CallOption) (*ListPortMappingsResponse, error)
	AddPortMapping(ctx context.Context, in *AddPortMappingRequest, opts ...grpc.CallOption) (*Empty, error)
	DeletePortMapping(ctx context.Context, in *DeletePortMappingRequest, opts ...grpc.CallOption) (*Empty, error)
	FindPortCandidates(ctx context.Context, in *FindPortCandidatesRequest, opts ...grpc.CallOption) (*FindPortCandidatesResponse, error)
	// Backup (optional)
	ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error)
	CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*Empty, error)
	RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*Empty, error)
	// Snapshot (optional)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*Empty, error)
	RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*Empty, error)
	// Firewall (optional)
	ListFirewallRules(ctx context.Context, in *ListFirewallRulesRequest, opts ...grpc.CallOption) (*ListFirewallRulesResponse, error)
	AddFirewallRule(ctx context.Context, in *AddFirewallRuleRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteFirewallRule(ctx context.Context, in *DeleteFirewallRuleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type automationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationServiceClient(cc grpc.ClientConnInterface) AutomationServiceClient {
	return &automationServiceClient{cc}
}

func (c *automationServiceClient) ListAreas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListAreasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAreasResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListAreas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListLines(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLinesResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListPackages(ctx context.Context, in *ListPackagesRequest, opts ...grpc.CallOption) (*ListPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPackagesResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, AutomationService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*GetInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListInstancesSimple(ctx context.Context, in *ListInstancesSimpleRequest, opts ...grpc.CallOption) (*ListInstancesSimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesSimpleResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListInstancesSimple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Reboot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Rebuild(ctx context.Context, in *RebuildRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Rebuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ElasticUpdate(ctx context.Context, in *ElasticUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_ElasticUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Lock(ctx context.Context, in *LockRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Lock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Unlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetPanelURL(ctx context.Context, in *GetPanelURLRequest, opts ...grpc.CallOption) (*GetPanelURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPanelURLResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetPanelURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetVNCURL(ctx context.Context, in *GetVNCURLRequest, opts ...grpc.CallOption) (*GetVNCURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVNCURLResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetVNCURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) GetMonitor(ctx context.Context, in *GetMonitorRequest, opts ...grpc.CallOption) (*GetMonitorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMonitorResponse)
	err := c.cc.Invoke(ctx, AutomationService_GetMonitor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListPortMappings(ctx context.Context, in *ListPortMappingsRequest, opts ...grpc.CallOption) (*ListPortMappingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPortMappingsResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListPortMappings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) AddPortMapping(ctx context.Context, in *AddPortMappingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_AddPortMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) DeletePortMapping(ctx context.Context, in *DeletePortMappingRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_DeletePortMapping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) FindPortCandidates(ctx context.Context, in *FindPortCandidatesRequest, opts ...grpc.CallOption) (*FindPortCandidatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPortCandidatesResponse)
	err := c.cc.Invoke(ctx, AutomationService_FindPortCandidates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListBackups(ctx context.Context, in *ListBackupsRequest, opts ...grpc.CallOption) (*ListBackupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackupsResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListBackups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) CreateBackup(ctx context.Context, in *CreateBackupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_CreateBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) DeleteBackup(ctx context.Context, in *DeleteBackupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_DeleteBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) RestoreBackup(ctx context.Context, in *RestoreBackupRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_RestoreBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) RestoreSnapshot(ctx context.Context, in *RestoreSnapshotRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_RestoreSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) ListFirewallRules(ctx context.Context, in *ListFirewallRulesRequest, opts ...grpc.CallOption) (*ListFirewallRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFirewallRulesResponse)
	err := c.cc.Invoke(ctx, AutomationService_ListFirewallRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) AddFirewallRule(ctx context.Context, in *AddFirewallRuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_AddFirewallRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationServiceClient) DeleteFirewallRule(ctx context.Context, in *DeleteFirewallRuleRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, AutomationService_DeleteFirewallRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationServiceServer is the server API for AutomationService service.
// All implementations must embed UnimplementedAutomationServiceServer
// for forward compatibility.
type AutomationServiceServer interface {
	// Catalog sync
	ListAreas(context.Context, *Empty) (*ListAreasResponse, error)
	ListLines(context.Context, *Empty) (*ListLinesResponse, error)
	ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// Instance lifecycle
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error)
	ListInstancesSimple(context.Context, *ListInstancesSimpleRequest) (*ListInstancesSimpleResponse, error)
	Start(context.Context, *StartRequest) (*Empty, error)
	Shutdown(context.Context, *ShutdownRequest) (*Empty, error)
	Reboot(context.Context, *RebootRequest) (*Empty, error)
	Rebuild(context.Context, *RebuildRequest) (*Empty, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*Empty, error)
	ElasticUpdate(context.Context, *ElasticUpdateRequest) (*Empty, error)
	Lock(context.Context, *LockRequest) (*Empty, error)
	Unlock(context.Context, *UnlockRequest) (*Empty, error)
	Renew(context.Context, *RenewRequest) (*Empty, error)
	Destroy(context.Context, *DestroyRequest) (*Empty, error)
	GetPanelURL(context.Context, *GetPanelURLRequest) (*GetPanelURLResponse, error)
	GetVNCURL(context.Context, *GetVNCURLRequest) (*GetVNCURLResponse, error)
	GetMonitor(context.Context, *GetMonitorRequest) (*GetMonitorResponse, error)
	// Port mapping (optional)
	ListPortMappings(context.Context, *ListPortMappingsRequest) (*ListPortMappingsResponse, error)
	AddPortMapping(context.Context, *AddPortMappingRequest) (*Empty, error)
	DeletePortMapping(context.Context, *DeletePortMappingRequest) (*Empty, error)
	FindPortCandidates(context.Context, *FindPortCandidatesRequest) (*FindPortCandidatesResponse, error)
	// Backup (optional)
	ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error)
	CreateBackup(context.Context, *CreateBackupRequest) (*Empty, error)
	DeleteBackup(context.Context, *DeleteBackupRequest) (*Empty, error)
	RestoreBackup(context.Context, *RestoreBackupRequest) (*Empty, error)
	// Snapshot (optional)
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Empty, error)
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*Empty, error)
	RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*Empty, error)
	// Firewall (optional)
	ListFirewallRules(context.Context, *ListFirewallRulesRequest) (*ListFirewallRulesResponse, error)
	AddFirewallRule(context.Context, *AddFirewallRuleRequest) (*Empty, error)
	DeleteFirewallRule(context.Context, *DeleteFirewallRuleRequest) (*Empty, error)
	mustEmbedUnimplementedAutomationServiceServer()
}

// UnimplementedAutomationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationServiceServer struct{}

func (UnimplementedAutomationServiceServer) ListAreas(context.Context, *Empty) (*ListAreasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAreas not implemented")
}
func (UnimplementedAutomationServiceServer) ListLines(context.Context, *Empty) (*ListLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLines not implemented")
}
func (UnimplementedAutomationServiceServer) ListPackages(context.Context, *ListPackagesRequest) (*ListPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPackages not implemented")
}
func (UnimplementedAutomationServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedAutomationServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedAutomationServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*GetInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedAutomationServiceServer) ListInstancesSimple(context.Context, *ListInstancesSimpleRequest) (*ListInstancesSimpleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstancesSimple not implemented")
}
func (UnimplementedAutomationServiceServer) Start(context.Context, *StartRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedAutomationServiceServer) Shutdown(context.Context, *ShutdownRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedAutomationServiceServer) Reboot(context.Context, *RebootRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedAutomationServiceServer) Rebuild(context.Context, *RebuildRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Rebuild not implemented")
}
func (UnimplementedAutomationServiceServer) ResetPassword(context.Context, *ResetPasswordRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedAutomationServiceServer) ElasticUpdate(context.Context, *ElasticUpdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ElasticUpdate not implemented")
}
func (UnimplementedAutomationServiceServer) Lock(context.Context, *LockRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Lock not implemented")
}
func (UnimplementedAutomationServiceServer) Unlock(context.Context, *UnlockRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedAutomationServiceServer) Renew(context.Context, *RenewRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedAutomationServiceServer) Destroy(context.Context, *DestroyRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedAutomationServiceServer) GetPanelURL(context.Context, *GetPanelURLRequest) (*GetPanelURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPanelURL not implemented")
}
func (UnimplementedAutomationServiceServer) GetVNCURL(context.Context, *GetVNCURLRequest) (*GetVNCURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVNCURL not implemented")
}
func (UnimplementedAutomationServiceServer) GetMonitor(context.Context, *GetMonitorRequest) (*GetMonitorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMonitor not implemented")
}
func (UnimplementedAutomationServiceServer) ListPortMappings(context.Context, *ListPortMappingsRequest) (*ListPortMappingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPortMappings not implemented")
}
func (UnimplementedAutomationServiceServer) AddPortMapping(context.Context, *AddPortMappingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPortMapping not implemented")
}
func (UnimplementedAutomationServiceServer) DeletePortMapping(context.Context, *DeletePortMappingRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePortMapping not implemented")
}
func (UnimplementedAutomationServiceServer) FindPortCandidates(context.Context, *FindPortCandidatesRequest) (*FindPortCandidatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPortCandidates not implemented")
}
func (UnimplementedAutomationServiceServer) ListBackups(context.Context, *ListBackupsRequest) (*ListBackupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackups not implemented")
}
func (UnimplementedAutomationServiceServer) CreateBackup(context.Context, *CreateBackupRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBackup not implemented")
}
func (UnimplementedAutomationServiceServer) DeleteBackup(context.Context, *DeleteBackupRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBackup not implemented")
}
func (UnimplementedAutomationServiceServer) RestoreBackup(context.Context, *RestoreBackupRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreBackup not implemented")
}
func (UnimplementedAutomationServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedAutomationServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedAutomationServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedAutomationServiceServer) RestoreSnapshot(context.Context, *RestoreSnapshotRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreSnapshot not implemented")
}
func (UnimplementedAutomationServiceServer) ListFirewallRules(context.Context, *ListFirewallRulesRequest) (*ListFirewallRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFirewallRules not implemented")
}
func (UnimplementedAutomationServiceServer) AddFirewallRule(context.Context, *AddFirewallRuleRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddFirewallRule not implemented")
}
func (UnimplementedAutomationServiceServer) DeleteFirewallRule(context.Context, *DeleteFirewallRuleRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFirewallRule not implemented")
}
func (UnimplementedAutomationServiceServer) mustEmbedUnimplementedAutomationServiceServer() {}
func (UnimplementedAutomationServiceServer) testEmbeddedByValue()                           {}

// UnsafeAutomationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationServiceServer will
// result in compilation errors.
type UnsafeAutomationServiceServer interface {
	mustEmbedUnimplementedAutomationServiceServer()
}

func RegisterAutomationServiceServer(s grpc.ServiceRegistrar, srv AutomationServiceServer) {
	// If the following call panics, it indicates UnimplementedAutomationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationService_ServiceDesc, srv)
}

func _AutomationService_ListAreas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListAreas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListAreas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListAreas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListLines(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListPackages(ctx, req.(*ListPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListInstancesSimple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesSimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListInstancesSimple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListInstancesSimple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListInstancesSimple(ctx, req.(*ListInstancesSimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Rebuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Rebuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Rebuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Rebuild(ctx, req.(*RebuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ElasticUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElasticUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ElasticUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ElasticUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ElasticUpdate(ctx, req.(*ElasticUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Lock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Lock(ctx, req.(*LockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Unlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetPanelURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPanelURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetPanelURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetPanelURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetPanelURL(ctx, req.(*GetPanelURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetVNCURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVNCURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetVNCURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetVNCURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetVNCURL(ctx, req.(*GetVNCURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_GetMonitor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonitorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).GetMonitor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_GetMonitor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).GetMonitor(ctx, req.(*GetMonitorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListPortMappings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPortMappingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListPortMappings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListPortMappings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListPortMappings(ctx, req.(*ListPortMappingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_AddPortMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPortMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).AddPortMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_AddPortMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).AddPortMapping(ctx, req.(*AddPortMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_DeletePortMapping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePortMappingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).DeletePortMapping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_DeletePortMapping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).DeletePortMapping(ctx, req.(*DeletePortMappingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_FindPortCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPortCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).FindPortCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_FindPortCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).FindPortCandidates(ctx, req.(*FindPortCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListBackups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListBackups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListBackups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListBackups(ctx, req.(*ListBackupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_CreateBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).CreateBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_CreateBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).CreateBackup(ctx, req.(*CreateBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_DeleteBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).DeleteBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_DeleteBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).DeleteBackup(ctx, req.(*DeleteBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_RestoreBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).RestoreBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_RestoreBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).RestoreBackup(ctx, req.(*RestoreBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_RestoreSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).RestoreSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_RestoreSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).RestoreSnapshot(ctx, req.(*RestoreSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_ListFirewallRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFirewallRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).ListFirewallRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_ListFirewallRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).ListFirewallRules(ctx, req.(*ListFirewallRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_AddFirewallRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFirewallRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).AddFirewallRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_AddFirewallRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).AddFirewallRule(ctx, req.(*AddFirewallRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationService_DeleteFirewallRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFirewallRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationServiceServer).DeleteFirewallRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationService_DeleteFirewallRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationServiceServer).DeleteFirewallRule(ctx, req.(*DeleteFirewallRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationService_ServiceDesc is the grpc.ServiceDesc for AutomationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.AutomationService",
	HandlerType: (*AutomationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAreas",
			Handler:    _AutomationService_ListAreas_Handler,
		},
		{
			MethodName: "ListLines",
			Handler:    _AutomationService_ListLines_Handler,
		},
		{
			MethodName: "ListPackages",
			Handler:    _AutomationService_ListPackages_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _AutomationService_ListImages_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _AutomationService_CreateInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _AutomationService_GetInstance_Handler,
		},
		{
			MethodName: "ListInstancesSimple",
			Handler:    _AutomationService_ListInstancesSimple_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _AutomationService_Start_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _AutomationService_Shutdown_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _AutomationService_Reboot_Handler,
		},
		{
			MethodName: "Rebuild",
			Handler:    _AutomationService_Rebuild_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AutomationService_ResetPassword_Handler,
		},
		{
			MethodName: "ElasticUpdate",
			Handler:    _AutomationService_ElasticUpdate_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _AutomationService_Lock_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _AutomationService_Unlock_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _AutomationService_Renew_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _AutomationService_Destroy_Handler,
		},
		{
			MethodName: "GetPanelURL",
			Handler:    _AutomationService_GetPanelURL_Handler,
		},
		{
			MethodName: "GetVNCURL",
			Handler:    _AutomationService_GetVNCURL_Handler,
		},
		{
			MethodName: "GetMonitor",
			Handler:    _AutomationService_GetMonitor_Handler,
		},
		{
			MethodName: "ListPortMappings",
			Handler:    _AutomationService_ListPortMappings_Handler,
		},
		{
			MethodName: "AddPortMapping",
			Handler:    _AutomationService_AddPortMapping_Handler,
		},
		{
			MethodName: "DeletePortMapping",
			Handler:    _AutomationService_DeletePortMapping_Handler,
		},
		{
			MethodName: "FindPortCandidates",
			Handler:    _AutomationService_FindPortCandidates_Handler,
		},
		{
			MethodName: "ListBackups",
			Handler:    _AutomationService_ListBackups_Handler,
		},
		{
			MethodName: "CreateBackup",
			Handler:    _AutomationService_CreateBackup_Handler,
		},
		{
			MethodName: "DeleteBackup",
			Handler:    _AutomationService_DeleteBackup_Handler,
		},
		{
			MethodName: "RestoreBackup",
			Handler:    _AutomationService_RestoreBackup_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _AutomationService_ListSnapshots_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _AutomationService_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _AutomationService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RestoreSnapshot",
			Handler:    _AutomationService_RestoreSnapshot_Handler,
		},
		{
			MethodName: "ListFirewallRules",
			Handler:    _AutomationService_ListFirewallRules_Handler,
		},
		{
			MethodName: "AddFirewallRule",
			Handler:    _AutomationService_AddFirewallRule_Handler,
		},
		{
			MethodName: "DeleteFirewallRule",
			Handler:    _AutomationService_DeleteFirewallRule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/v1/automation.proto",
}
