// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plugin/v1/core.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_plugin_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_plugin_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_plugin_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InitRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_plugin_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_plugin_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_plugin_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadConfigResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReloadConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_v1_core_proto protoreflect.FileDescriptor

const file_plugin_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x14plugin/v1/core.proto\x12\tplugin.v1\x1a\x15plugin/v1/types.proto\x1a\x18plugin/v1/manifest.proto\"8\n" +
	"\x15ValidateConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\">\n" +
	"\x16ValidateConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"O\n" +
	"\vInitRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\"4\n" +
	"\fInitResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\x13ReloadConfigRequest\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"<\n" +
	"\x14ReloadConfigResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xab\x03\n" +
	"\vCoreService\x124\n" +
	"\vGetManifest\x12\x10.plugin.v1.Empty\x1a\x13.plugin.v1.Manifest\x12<\n" +
	"\x0fGetConfigSchema\x12\x10.plugin.v1.Empty\x1a\x17.plugin.v1.ConfigSchema\x12U\n" +
	"\x0eValidateConfig\x12 .plugin.v1.ValidateConfigRequest\x1a!.plugin.v1.ValidateConfigResponse\x127\n" +
	"\x04Init\x12\x16.plugin.v1.InitRequest\x1a\x17.plugin.v1.InitResponse\x12O\n" +
	"\fReloadConfig\x12\x1e.plugin.v1.ReloadConfigRequest\x1a\x1f.plugin.v1.ReloadConfigResponse\x12G\n" +
	"\x06Health\x12\x1d.plugin.v1.HealthCheckRequest\x1a\x1e.plugin.v1.HealthCheckResponseB Z\x1exiaoheiplay/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_core_proto_rawDescOnce sync.Once
	file_plugin_v1_core_proto_rawDescData []byte
)

func file_plugin_v1_core_proto_rawDescGZIP() []byte {
	file_plugin_v1_core_proto_rawDescOnce.Do(func() {
		file_plugin_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_core_proto_rawDesc), len(file_plugin_v1_core_proto_rawDesc)))
	})
	return file_plugin_v1_core_proto_rawDescData
}

var file_plugin_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_plugin_v1_core_proto_goTypes = []any{
	(*ValidateConfigRequest)(nil),  // 0: plugin.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil), // 1: plugin.v1.ValidateConfigResponse
	(*InitRequest)(nil),            // 2: plugin.v1.InitRequest
	(*InitResponse)(nil),           // 3: plugin.v1.InitResponse
	(*ReloadConfigRequest)(nil),    // 4: plugin.v1.ReloadConfigRequest
	(*ReloadConfigResponse)(nil),   // 5: plugin.v1.ReloadConfigResponse
	(*Empty)(nil),                  // 6: plugin.v1.Empty
	(*HealthCheckRequest)(nil),     // 7: plugin.v1.HealthCheckRequest
	(*Manifest)(nil),               // 8: plugin.v1.Manifest
	(*ConfigSchema)(nil),           // 9: plugin.v1.ConfigSchema
	(*HealthCheckResponse)(nil),    // 10: plugin.v1.HealthCheckResponse
}
var file_plugin_v1_core_proto_depIdxs = []int32{
	6,  // 0: plugin.v1.CoreService.GetManifest:input_type -> plugin.v1.Empty
	6,  // 1: plugin.v1.CoreService.GetConfigSchema:input_type -> plugin.v1.Empty
	0,  // 2: plugin.v1.CoreService.ValidateConfig:input_type -> plugin.v1.ValidateConfigRequest
	2,  // 3: plugin.v1.CoreService.Init:input_type -> plugin.v1.InitRequest
	4,  // 4: plugin.v1.CoreService.ReloadConfig:input_type -> plugin.v1.ReloadConfigRequest
	7,  // 5: plugin.v1.CoreService.Health:input_type -> plugin.v1.HealthCheckRequest
	8,  // 6: plugin.v1.CoreService.GetManifest:output_type -> plugin.v1.Manifest
	9,  // 7: plugin.v1.CoreService.GetConfigSchema:output_type -> plugin.v1.ConfigSchema
	1,  // 8: plugin.v1.CoreService.ValidateConfig:output_type -> plugin.v1.ValidateConfigResponse
	3,  // 9: plugin.v1.CoreService.Init:output_type -> plugin.v1.InitResponse
	5,  // 10: plugin.v1.CoreService.ReloadConfig:output_type -> plugin.v1.ReloadConfigResponse
	10, // 11: plugin.v1.CoreService.Health:output_type -> plugin.v1.HealthCheckResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_v1_core_proto_init() }
func file_plugin_v1_core_proto_init() {
	if File_plugin_v1_core_proto != nil {
		return
	}
	file_plugin_v1_types_proto_init()
	file_plugin_v1_manifest_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_core_proto_rawDesc), len(file_plugin_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_core_proto_goTypes,
		DependencyIndexes: file_plugin_v1_core_proto_depIdxs,
		MessageInfos:      file_plugin_v1_core_proto_msgTypes,
	}.Build()
	File_plugin_v1_core_proto = out.File
	file_plugin_v1_core_proto_goTypes = nil
	file_plugin_v1_core_proto_depIdxs = nil
}
