// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plugin/v1/kyc.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KycStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Params        map[string]string      `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycStartRequest) Reset() {
	*x = KycStartRequest{}
	mi := &file_plugin_v1_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycStartRequest) ProtoMessage() {}

func (x *KycStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycStartRequest.ProtoReflect.Descriptor instead.
func (*KycStartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *KycStartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *KycStartRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type KycStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	NextStep      string                 `protobuf:"bytes,4,opt,name=next_step,json=nextStep,proto3" json:"next_step,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycStartResponse) Reset() {
	*x = KycStartResponse{}
	mi := &file_plugin_v1_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycStartResponse) ProtoMessage() {}

func (x *KycStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycStartResponse.ProtoReflect.Descriptor instead.
func (*KycStartResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *KycStartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *KycStartResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *KycStartResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *KycStartResponse) GetNextStep() string {
	if x != nil {
		return x.NextStep
	}
	return ""
}

func (x *KycStartResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type KycQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycQueryRequest) Reset() {
	*x = KycQueryRequest{}
	mi := &file_plugin_v1_kyc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycQueryRequest) ProtoMessage() {}

func (x *KycQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_kyc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycQueryRequest.ProtoReflect.Descriptor instead.
func (*KycQueryRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_kyc_proto_rawDescGZIP(), []int{2}
}

func (x *KycQueryRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type KycQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RawJson       string                 `protobuf:"bytes,4,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KycQueryResponse) Reset() {
	*x = KycQueryResponse{}
	mi := &file_plugin_v1_kyc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KycQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KycQueryResponse) ProtoMessage() {}

func (x *KycQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_kyc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KycQueryResponse.ProtoReflect.Descriptor instead.
func (*KycQueryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_kyc_proto_rawDescGZIP(), []int{3}
}

func (x *KycQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *KycQueryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *KycQueryResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KycQueryResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *KycQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_v1_kyc_proto protoreflect.FileDescriptor

const file_plugin_v1_kyc_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/v1/kyc.proto\x12\tplugin.v1\"\xa5\x01\n" +
	"\x0fKycStartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12>\n" +
	"\x06params\x18\x02 \x03(\v2&.plugin.v1.KycStartRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x10KycStartResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1b\n" +
	"\tnext_step\x18\x04 \x01(\tR\bnextStep\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"'\n" +
	"\x0fKycQueryRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x83\x01\n" +
	"\x10KycQueryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\braw_json\x18\x04 \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\x96\x01\n" +
	"\n" +
	"KycService\x12@\n" +
	"\x05Start\x12\x1a.plugin.v1.KycStartRequest\x1a\x1b.plugin.v1.KycStartResponse\x12F\n" +
	"\vQueryResult\x12\x1a.plugin.v1.KycQueryRequest\x1a\x1b.plugin.v1.KycQueryResponseB Z\x1exiaoheiplay/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_kyc_proto_rawDescOnce sync.Once
	file_plugin_v1_kyc_proto_rawDescData []byte
)

func file_plugin_v1_kyc_proto_rawDescGZIP() []byte {
	file_plugin_v1_kyc_proto_rawDescOnce.Do(func() {
		file_plugin_v1_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_kyc_proto_rawDesc), len(file_plugin_v1_kyc_proto_rawDesc)))
	})
	return file_plugin_v1_kyc_proto_rawDescData
}

var file_plugin_v1_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_v1_kyc_proto_goTypes = []any{
	(*KycStartRequest)(nil),  // 0: plugin.v1.KycStartRequest
	(*KycStartResponse)(nil), // 1: plugin.v1.KycStartResponse
	(*KycQueryRequest)(nil),  // 2: plugin.v1.KycQueryRequest
	(*KycQueryResponse)(nil), // 3: plugin.v1.KycQueryResponse
	nil,                      // 4: plugin.v1.KycStartRequest.ParamsEntry
}
var file_plugin_v1_kyc_proto_depIdxs = []int32{
	4, // 0: plugin.v1.KycStartRequest.params:type_name -> plugin.v1.KycStartRequest.ParamsEntry
	0, // 1: plugin.v1.KycService.Start:input_type -> plugin.v1.KycStartRequest
	2, // 2: plugin.v1.KycService.QueryResult:input_type -> plugin.v1.KycQueryRequest
	1, // 3: plugin.v1.KycService.Start:output_type -> plugin.v1.KycStartResponse
	3, // 4: plugin.v1.KycService.QueryResult:output_type -> plugin.v1.KycQueryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_v1_kyc_proto_init() }
func file_plugin_v1_kyc_proto_init() {
	if File_plugin_v1_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_kyc_proto_rawDesc), len(file_plugin_v1_kyc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_kyc_proto_goTypes,
		DependencyIndexes: file_plugin_v1_kyc_proto_depIdxs,
		MessageInfos:      file_plugin_v1_kyc_proto_msgTypes,
	}.Build()
	File_plugin_v1_kyc_proto = out.File
	file_plugin_v1_kyc_proto_goTypes = nil
	file_plugin_v1_kyc_proto_depIdxs = nil
}
