// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plugin/v1/payment.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_PAID        PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDING   PaymentStatus = 4
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 5
	PaymentStatus_PAYMENT_STATUS_CLOSED      PaymentStatus = 6
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_PAID",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_REFUNDING",
		5: "PAYMENT_STATUS_REFUNDED",
		6: "PAYMENT_STATUS_CLOSED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_PAID":        2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_REFUNDING":   4,
		"PAYMENT_STATUS_REFUNDED":    5,
		"PAYMENT_STATUS_CLOSED":      6,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_payment_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_plugin_v1_payment_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{0}
}

type ListMethodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMethodsResponse) Reset() {
	*x = ListMethodsResponse{}
	mi := &file_plugin_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMethodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMethodsResponse) ProtoMessage() {}

func (x *ListMethodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMethodsResponse.ProtoReflect.Descriptor instead.
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ListMethodsResponse) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *ListMethodsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListMethodsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ListMethodsResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type PaymentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,6,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	NotifyUrl     string                 `protobuf:"bytes,7,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,8,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateRequest) Reset() {
	*x = PaymentCreateRequest{}
	mi := &file_plugin_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateRequest) ProtoMessage() {}

func (x *PaymentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateRequest.ProtoReflect.Descriptor instead.
func (*PaymentCreateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentCreateRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *PaymentCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentCreateRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentCreateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentCreateRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PaymentCreateRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PaymentCreateRequest) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PaymentCreateRequest) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type CreatePaymentRpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Request       *PaymentCreateRequest  `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRpcRequest) Reset() {
	*x = CreatePaymentRpcRequest{}
	mi := &file_plugin_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRpcRequest) ProtoMessage() {}

func (x *CreatePaymentRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRpcRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRpcRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePaymentRpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePaymentRpcRequest) GetRequest() *PaymentCreateRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type PaymentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	PayUrl        string                 `protobuf:"bytes,3,opt,name=pay_url,json=payUrl,proto3" json:"pay_url,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,4,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentCreateResponse) Reset() {
	*x = PaymentCreateResponse{}
	mi := &file_plugin_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateResponse) ProtoMessage() {}

func (x *PaymentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateResponse.ProtoReflect.Descriptor instead.
func (*PaymentCreateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCreateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PaymentCreateResponse) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentCreateResponse) GetPayUrl() string {
	if x != nil {
		return x.PayUrl
	}
	return ""
}

func (x *PaymentCreateResponse) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *PaymentCreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PaymentCreateResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type QueryPaymentRpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRpcRequest) Reset() {
	*x = QueryPaymentRpcRequest{}
	mi := &file_plugin_v1_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRpcRequest) ProtoMessage() {}

func (x *QueryPaymentRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRpcRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRpcRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{4}
}

func (x *QueryPaymentRpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *QueryPaymentRpcRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *QueryPaymentRpcRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

type PaymentQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=plugin.v1.PaymentStatus" json:"status,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	RawJson       string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,20,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,21,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentQueryResponse) Reset() {
	*x = PaymentQueryResponse{}
	mi := &file_plugin_v1_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentQueryResponse) ProtoMessage() {}

func (x *PaymentQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentQueryResponse.ProtoReflect.Descriptor instead.
func (*PaymentQueryResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentQueryResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PaymentQueryResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PaymentQueryResponse) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PaymentQueryResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentQueryResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *PaymentQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PaymentQueryResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type RefundRpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	TradeNo       string                 `protobuf:"bytes,2,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	RefundNo      string                 `protobuf:"bytes,3,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRpcRequest) Reset() {
	*x = RefundRpcRequest{}
	mi := &file_plugin_v1_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRpcRequest) ProtoMessage() {}

func (x *RefundRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRpcRequest.ProtoReflect.Descriptor instead.
func (*RefundRpcRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{6}
}

func (x *RefundRpcRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RefundRpcRequest) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *RefundRpcRequest) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundRpcRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRpcRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RefundNo      string                 `protobuf:"bytes,2,opt,name=refund_no,json=refundNo,proto3" json:"refund_no,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=plugin.v1.PaymentStatus" json:"status,omitempty"`
	RawJson       string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,20,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,21,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_plugin_v1_payment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{7}
}

func (x *RefundResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RefundResponse) GetRefundNo() string {
	if x != nil {
		return x.RefundNo
	}
	return ""
}

func (x *RefundResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *RefundResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *RefundResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RefundResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type VerifyNotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Raw           *RawHttpRequest        `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNotifyRequest) Reset() {
	*x = VerifyNotifyRequest{}
	mi := &file_plugin_v1_payment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNotifyRequest) ProtoMessage() {}

func (x *VerifyNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNotifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyNotifyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyNotifyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *VerifyNotifyRequest) GetRaw() *RawHttpRequest {
	if x != nil {
		return x.Raw
	}
	return nil
}

type NotifyVerifyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	OrderNo       string                 `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	TradeNo       string                 `protobuf:"bytes,3,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=plugin.v1.PaymentStatus" json:"status,omitempty"`
	PaidAtUnix    int64                  `protobuf:"varint,6,opt,name=paid_at_unix,json=paidAtUnix,proto3" json:"paid_at_unix,omitempty"`
	Payer         string                 `protobuf:"bytes,7,opt,name=payer,proto3" json:"payer,omitempty"`
	RawJson       string                 `protobuf:"bytes,20,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	AckBody       string                 `protobuf:"bytes,21,opt,name=ack_body,json=ackBody,proto3" json:"ack_body,omitempty"`
	Error         string                 `protobuf:"bytes,30,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,31,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyVerifyResult) Reset() {
	*x = NotifyVerifyResult{}
	mi := &file_plugin_v1_payment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyVerifyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyVerifyResult) ProtoMessage() {}

func (x *NotifyVerifyResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_payment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyVerifyResult.ProtoReflect.Descriptor instead.
func (*NotifyVerifyResult) Descriptor() ([]byte, []int) {
	return file_plugin_v1_payment_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyVerifyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *NotifyVerifyResult) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *NotifyVerifyResult) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *NotifyVerifyResult) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NotifyVerifyResult) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *NotifyVerifyResult) GetPaidAtUnix() int64 {
	if x != nil {
		return x.PaidAtUnix
	}
	return 0
}

func (x *NotifyVerifyResult) GetPayer() string {
	if x != nil {
		return x.Payer
	}
	return ""
}

func (x *NotifyVerifyResult) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *NotifyVerifyResult) GetAckBody() string {
	if x != nil {
		return x.AckBody
	}
	return ""
}

func (x *NotifyVerifyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NotifyVerifyResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_plugin_v1_payment_proto protoreflect.FileDescriptor

const file_plugin_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x17plugin/v1/payment.proto\x12\tplugin.v1\x1a\x15plugin/v1/types.proto\"t\n" +
	"\x13ListMethodsResponse\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\xd2\x02\n" +
	"\x14PaymentCreateRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"return_url\x18\x06 \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"notify_url\x18\a \x01(\tR\tnotifyUrl\x12@\n" +
	"\x05extra\x18\b \x03(\v2*.plugin.v1.PaymentCreateRequest.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x17CreatePaymentRpcRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x129\n" +
	"\arequest\x18\x02 \x01(\v2\x1f.plugin.v1.PaymentCreateRequestR\arequest\"\x8d\x02\n" +
	"\x15PaymentCreateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\x17\n" +
	"\apay_url\x18\x03 \x01(\tR\x06payUrl\x12A\n" +
	"\x05extra\x18\x04 \x03(\v2+.plugin.v1.PaymentCreateResponse.ExtraEntryR\x05extra\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x16QueryPaymentRpcRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\"\xdb\x01\n" +
	"\x14PaymentQueryResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.plugin.v1.PaymentStatusR\x06status\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x14 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x15 \x01(\tR\terrorCode\"\x92\x01\n" +
	"\x10RefundRpcRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x19\n" +
	"\btrade_no\x18\x02 \x01(\tR\atradeNo\x12\x1b\n" +
	"\trefund_no\x18\x03 \x01(\tR\brefundNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xbf\x01\n" +
	"\x0eRefundResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1b\n" +
	"\trefund_no\x18\x02 \x01(\tR\brefundNo\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.plugin.v1.PaymentStatusR\x06status\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x14 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x15 \x01(\tR\terrorCode\"Z\n" +
	"\x13VerifyNotifyRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12+\n" +
	"\x03raw\x18\x02 \x01(\v2\x19.plugin.v1.RawHttpRequestR\x03raw\"\xc7\x02\n" +
	"\x12NotifyVerifyResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x19\n" +
	"\border_no\x18\x02 \x01(\tR\aorderNo\x12\x19\n" +
	"\btrade_no\x18\x03 \x01(\tR\atradeNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.plugin.v1.PaymentStatusR\x06status\x12 \n" +
	"\fpaid_at_unix\x18\x06 \x01(\x03R\n" +
	"paidAtUnix\x12\x14\n" +
	"\x05payer\x18\a \x01(\tR\x05payer\x12\x19\n" +
	"\braw_json\x18\x14 \x01(\tR\arawJson\x12\x19\n" +
	"\back_body\x18\x15 \x01(\tR\aackBody\x12\x14\n" +
	"\x05error\x18\x1e \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x1f \x01(\tR\terrorCode*\xd5\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13PAYMENT_STATUS_PAID\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18PAYMENT_STATUS_REFUNDING\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_STATUS_REFUNDED\x10\x05\x12\x19\n" +
	"\x15PAYMENT_STATUS_CLOSED\x10\x062\x8d\x03\n" +
	"\x0ePaymentService\x12?\n" +
	"\vListMethods\x12\x10.plugin.v1.Empty\x1a\x1e.plugin.v1.ListMethodsResponse\x12U\n" +
	"\rCreatePayment\x12\".plugin.v1.CreatePaymentRpcRequest\x1a .plugin.v1.PaymentCreateResponse\x12R\n" +
	"\fQueryPayment\x12!.plugin.v1.QueryPaymentRpcRequest\x1a\x1f.plugin.v1.PaymentQueryResponse\x12@\n" +
	"\x06Refund\x12\x1b.plugin.v1.RefundRpcRequest\x1a\x19.plugin.v1.RefundResponse\x12M\n" +
	"\fVerifyNotify\x12\x1e.plugin.v1.VerifyNotifyRequest\x1a\x1d.plugin.v1.NotifyVerifyResultB Z\x1exiaoheiplay/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_payment_proto_rawDescOnce sync.Once
	file_plugin_v1_payment_proto_rawDescData []byte
)

func file_plugin_v1_payment_proto_rawDescGZIP() []byte {
	file_plugin_v1_payment_proto_rawDescOnce.Do(func() {
		file_plugin_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_payment_proto_rawDesc), len(file_plugin_v1_payment_proto_rawDesc)))
	})
	return file_plugin_v1_payment_proto_rawDescData
}

var file_plugin_v1_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_plugin_v1_payment_proto_goTypes = []any{
	(PaymentStatus)(0),              // 0: plugin.v1.PaymentStatus
	(*ListMethodsResponse)(nil),     // 1: plugin.v1.ListMethodsResponse
	(*PaymentCreateRequest)(nil),    // 2: plugin.v1.PaymentCreateRequest
	(*CreatePaymentRpcRequest)(nil), // 3: plugin.v1.CreatePaymentRpcRequest
	(*PaymentCreateResponse)(nil),   // 4: plugin.v1.PaymentCreateResponse
	(*QueryPaymentRpcRequest)(nil),  // 5: plugin.v1.QueryPaymentRpcRequest
	(*PaymentQueryResponse)(nil),    // 6: plugin.v1.PaymentQueryResponse
	(*RefundRpcRequest)(nil),        // 7: plugin.v1.RefundRpcRequest
	(*RefundResponse)(nil),          // 8: plugin.v1.RefundResponse
	(*VerifyNotifyRequest)(nil),     // 9: plugin.v1.VerifyNotifyRequest
	(*NotifyVerifyResult)(nil),      // 10: plugin.v1.NotifyVerifyResult
	nil,                             // 11: plugin.v1.PaymentCreateRequest.ExtraEntry
	nil,                             // 12: plugin.v1.PaymentCreateResponse.ExtraEntry
	(*RawHttpRequest)(nil),          // 13: plugin.v1.RawHttpRequest
	(*Empty)(nil),                   // 14: plugin.v1.Empty
}
var file_plugin_v1_payment_proto_depIdxs = []int32{
	11, // 0: plugin.v1.PaymentCreateRequest.extra:type_name -> plugin.v1.PaymentCreateRequest.ExtraEntry
	2,  // 1: plugin.v1.CreatePaymentRpcRequest.request:type_name -> plugin.v1.PaymentCreateRequest
	12, // 2: plugin.v1.PaymentCreateResponse.extra:type_name -> plugin.v1.PaymentCreateResponse.ExtraEntry
	0,  // 3: plugin.v1.PaymentQueryResponse.status:type_name -> plugin.v1.PaymentStatus
	0,  // 4: plugin.v1.RefundResponse.status:type_name -> plugin.v1.PaymentStatus
	13, // 5: plugin.v1.VerifyNotifyRequest.raw:type_name -> plugin.v1.RawHttpRequest
	0,  // 6: plugin.v1.NotifyVerifyResult.status:type_name -> plugin.v1.PaymentStatus
	14, // 7: plugin.v1.PaymentService.ListMethods:input_type -> plugin.v1.Empty
	3,  // 8: plugin.v1.PaymentService.CreatePayment:input_type -> plugin.v1.CreatePaymentRpcRequest
	5,  // 9: plugin.v1.PaymentService.QueryPayment:input_type -> plugin.v1.QueryPaymentRpcRequest
	7,  // 10: plugin.v1.PaymentService.Refund:input_type -> plugin.v1.RefundRpcRequest
	9,  // 11: plugin.v1.PaymentService.VerifyNotify:input_type -> plugin.v1.VerifyNotifyRequest
	1,  // 12: plugin.v1.PaymentService.ListMethods:output_type -> plugin.v1.ListMethodsResponse
	4,  // 13: plugin.v1.PaymentService.CreatePayment:output_type -> plugin.v1.PaymentCreateResponse
	6,  // 14: plugin.v1.PaymentService.QueryPayment:output_type -> plugin.v1.PaymentQueryResponse
	8,  // 15: plugin.v1.PaymentService.Refund:output_type -> plugin.v1.RefundResponse
	10, // 16: plugin.v1.PaymentService.VerifyNotify:output_type -> plugin.v1.NotifyVerifyResult
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_plugin_v1_payment_proto_init() }
func file_plugin_v1_payment_proto_init() {
	if File_plugin_v1_payment_proto != nil {
		return
	}
	file_plugin_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_payment_proto_rawDesc), len(file_plugin_v1_payment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_payment_proto_goTypes,
		DependencyIndexes: file_plugin_v1_payment_proto_depIdxs,
		EnumInfos:         file_plugin_v1_payment_proto_enumTypes,
		MessageInfos:      file_plugin_v1_payment_proto_msgTypes,
	}.Build()
	File_plugin_v1_payment_proto = out.File
	file_plugin_v1_payment_proto_goTypes = nil
	file_plugin_v1_payment_proto_depIdxs = nil
}
