// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plugin/v1/sms.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Vars          map[string]string      `protobuf:"bytes,2,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Phones        []string               `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsRequest) Reset() {
	*x = SendSmsRequest{}
	mi := &file_plugin_v1_sms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsRequest) ProtoMessage() {}

func (x *SendSmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_sms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsRequest.ProtoReflect.Descriptor instead.
func (*SendSmsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_sms_proto_rawDescGZIP(), []int{0}
}

func (x *SendSmsRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *SendSmsRequest) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *SendSmsRequest) GetPhones() []string {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *SendSmsRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type SendSmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSmsResponse) Reset() {
	*x = SendSmsResponse{}
	mi := &file_plugin_v1_sms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSmsResponse) ProtoMessage() {}

func (x *SendSmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_sms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSmsResponse.ProtoReflect.Descriptor instead.
func (*SendSmsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_sms_proto_rawDescGZIP(), []int{1}
}

func (x *SendSmsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SendSmsResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendSmsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_plugin_v1_sms_proto protoreflect.FileDescriptor

const file_plugin_v1_sms_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/v1/sms.proto\x12\tplugin.v1\"\xd5\x01\n" +
	"\x0eSendSmsRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x127\n" +
	"\x04vars\x18\x02 \x03(\v2#.plugin.v1.SendSmsRequest.VarsEntryR\x04vars\x12\x16\n" +
	"\x06phones\x18\x03 \x03(\tR\x06phones\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x0fSendSmsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2K\n" +
	"\n" +
	"SmsService\x12=\n" +
	"\x04Send\x12\x19.plugin.v1.SendSmsRequest\x1a\x1a.plugin.v1.SendSmsResponseB Z\x1exiaoheiplay/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_sms_proto_rawDescOnce sync.Once
	file_plugin_v1_sms_proto_rawDescData []byte
)

func file_plugin_v1_sms_proto_rawDescGZIP() []byte {
	file_plugin_v1_sms_proto_rawDescOnce.Do(func() {
		file_plugin_v1_sms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_sms_proto_rawDesc), len(file_plugin_v1_sms_proto_rawDesc)))
	})
	return file_plugin_v1_sms_proto_rawDescData
}

var file_plugin_v1_sms_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_v1_sms_proto_goTypes = []any{
	(*SendSmsRequest)(nil),  // 0: plugin.v1.SendSmsRequest
	(*SendSmsResponse)(nil), // 1: plugin.v1.SendSmsResponse
	nil,                     // 2: plugin.v1.SendSmsRequest.VarsEntry
}
var file_plugin_v1_sms_proto_depIdxs = []int32{
	2, // 0: plugin.v1.SendSmsRequest.vars:type_name -> plugin.v1.SendSmsRequest.VarsEntry
	0, // 1: plugin.v1.SmsService.Send:input_type -> plugin.v1.SendSmsRequest
	1, // 2: plugin.v1.SmsService.Send:output_type -> plugin.v1.SendSmsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_v1_sms_proto_init() }
func file_plugin_v1_sms_proto_init() {
	if File_plugin_v1_sms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_sms_proto_rawDesc), len(file_plugin_v1_sms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_sms_proto_goTypes,
		DependencyIndexes: file_plugin_v1_sms_proto_depIdxs,
		MessageInfos:      file_plugin_v1_sms_proto_msgTypes,
	}.Build()
	File_plugin_v1_sms_proto = out.File
	file_plugin_v1_sms_proto_goTypes = nil
	file_plugin_v1_sms_proto_depIdxs = nil
}
