// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plugin/v1/types.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_OK          HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_ERROR       HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_OK",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_ERROR",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_OK":          1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_ERROR":       3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_v1_types_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_plugin_v1_types_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unified operation response for optional business-level status.
	// Backward compatible: old plugins can still return an empty message.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg           string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Other         string `protobuf:"bytes,3,opt,name=other,proto3" json:"other,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Empty) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Empty) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Empty) GetOther() string {
	if x != nil {
		return x.Other
	}
	return ""
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_plugin_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// RawHttpRequest is the original HTTP callback request passed from host -> plugin.
// The host should forward these fields "as-is" (no signature parsing in host).
type RawHttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery      string                 `protobuf:"bytes,3,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawHttpRequest) Reset() {
	*x = RawHttpRequest{}
	mi := &file_plugin_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawHttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawHttpRequest) ProtoMessage() {}

func (x *RawHttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawHttpRequest.ProtoReflect.Descriptor instead.
func (*RawHttpRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *RawHttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RawHttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RawHttpRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *RawHttpRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RawHttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_plugin_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=plugin.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UnixMillis    int64                  `protobuf:"varint,3,opt,name=unix_millis,json=unixMillis,proto3" json:"unix_millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_plugin_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthCheckResponse) GetUnixMillis() int64 {
	if x != nil {
		return x.UnixMillis
	}
	return 0
}

type ConfigSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonSchema    string                 `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	UiSchema      string                 `protobuf:"bytes,2,opt,name=ui_schema,json=uiSchema,proto3" json:"ui_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_plugin_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_plugin_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *ConfigSchema) GetJsonSchema() string {
	if x != nil {
		return x.JsonSchema
	}
	return ""
}

func (x *ConfigSchema) GetUiSchema() string {
	if x != nil {
		return x.UiSchema
	}
	return ""
}

var File_plugin_v1_types_proto protoreflect.FileDescriptor

const file_plugin_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15plugin/v1/types.proto\x12\tplugin.v1\"G\n" +
	"\x05Empty\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x14\n" +
	"\x05other\x18\x03 \x01(\tR\x05other\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x82\x02\n" +
	"\x0eRawHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x03 \x01(\tR\brawQuery\x12@\n" +
	"\aheaders\x18\x04 \x03(\v2&.plugin.v1.RawHttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x1aQ\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.plugin.v1.StringListR\x05value:\x028\x01\"5\n" +
	"\x12HealthCheckRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x81\x01\n" +
	"\x13HealthCheckResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.plugin.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vunix_millis\x18\x03 \x01(\x03R\n" +
	"unixMillis\"L\n" +
	"\fConfigSchema\x12\x1f\n" +
	"\vjson_schema\x18\x01 \x01(\tR\n" +
	"jsonSchema\x12\x1b\n" +
	"\tui_schema\x18\x02 \x01(\tR\buiSchema*x\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10HEALTH_STATUS_OK\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x17\n" +
	"\x13HEALTH_STATUS_ERROR\x10\x03B Z\x1exiaoheiplay/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_types_proto_rawDescOnce sync.Once
	file_plugin_v1_types_proto_rawDescData []byte
)

func file_plugin_v1_types_proto_rawDescGZIP() []byte {
	file_plugin_v1_types_proto_rawDescOnce.Do(func() {
		file_plugin_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_types_proto_rawDesc), len(file_plugin_v1_types_proto_rawDesc)))
	})
	return file_plugin_v1_types_proto_rawDescData
}

var file_plugin_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_v1_types_proto_goTypes = []any{
	(HealthStatus)(0),           // 0: plugin.v1.HealthStatus
	(*Empty)(nil),               // 1: plugin.v1.Empty
	(*StringList)(nil),          // 2: plugin.v1.StringList
	(*RawHttpRequest)(nil),      // 3: plugin.v1.RawHttpRequest
	(*HealthCheckRequest)(nil),  // 4: plugin.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 5: plugin.v1.HealthCheckResponse
	(*ConfigSchema)(nil),        // 6: plugin.v1.ConfigSchema
	nil,                         // 7: plugin.v1.RawHttpRequest.HeadersEntry
}
var file_plugin_v1_types_proto_depIdxs = []int32{
	7, // 0: plugin.v1.RawHttpRequest.headers:type_name -> plugin.v1.RawHttpRequest.HeadersEntry
	0, // 1: plugin.v1.HealthCheckResponse.status:type_name -> plugin.v1.HealthStatus
	2, // 2: plugin.v1.RawHttpRequest.HeadersEntry.value:type_name -> plugin.v1.StringList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_v1_types_proto_init() }
func file_plugin_v1_types_proto_init() {
	if File_plugin_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_types_proto_rawDesc), len(file_plugin_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_v1_types_proto_goTypes,
		DependencyIndexes: file_plugin_v1_types_proto_depIdxs,
		EnumInfos:         file_plugin_v1_types_proto_enumTypes,
		MessageInfos:      file_plugin_v1_types_proto_msgTypes,
	}.Build()
	File_plugin_v1_types_proto = out.File
	file_plugin_v1_types_proto_goTypes = nil
	file_plugin_v1_types_proto_depIdxs = nil
}
